<Project>
  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <Authors>Offside</Authors>
    <RepositoryUrl>https://github.com/vpcam/Offside</RepositoryUrl>
  </PropertyGroup>
</Project>
